### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by jaaronbr** [cebarks/TuneView#2]
As a user
When I visit "/"
Then I should see a link that is styled like a button that says "Sign In w Spotify"
And when I click on "Sign In w Spotify"
Then I should go through the OAuth process
And I should be redirected to /dashboard

and should see a logged in message "Successfully signed in."

Required by #3
Required by #4
Closes #2

**Comment by SyntheticAutomation** [comment]
pair programming approval
